# Generated by Django 2.0.2 on 2018-04-01 16:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questionizer', '0003_auto_20180401_0010'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
